# Generated by Django 2.2.3 on 2019-08-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hakertoneapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teamcode',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
