# Generated by Django 2.2.3 on 2019-08-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hakertoneapp', '0002_team_teamcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamcode',
            field=models.CharField(max_length=10),
        ),
    ]
