# Generated by Django 2.2.4 on 2019-08-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hakertoneapp', '0003_auto_20190809_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='userName',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
