# Generated by Django 2.2.3 on 2019-08-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hakertoneapp', '0004_auto_20190810_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='howmany',
        ),
    ]
